#!/bin/bash

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi

# install Pathogen
#mkdir -p ~/.vim/autoload ~/.vim/bundle
#curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle

declare -a packages=(
  "https://tpope.io/vim/dispatch.git"
  "https://github.com/ntpeters/vim-better-whitespace.git"
  "https://github.com/terryma/vim-multiple-cursors.git"
  "https://github.com/junegunn/fzf.vim.git"
  "https://github.com/vim-airline/vim-airline"
  "https://github.com/vim-airline/vim-airline-themes"
  "https://github.com/tpope/vim-fugitive"
  "https://github.com/airblade/vim-gitgutter"
  "https://github.com/tomtom/tlib_vim.git"
  "https://github.com/MarcWeber/vim-addon-mw-utils.git"
  "https://github.com/garbas/vim-snipmate.git"
  "https://github.com/honza/vim-snippets.git"
  "https://github.com/majutsushi/tagbar.git"
  "https://github.com/scrooloose/nerdcommenter.git"
  "https://github.com/morhetz/gruvbox.git"
)

for package in ${packages[@]}
do
  echo "Installing ${package}"
  if git clone ${package} > /dev/null 2>&1 ; then
    echo "${package} installed successfully"
  else
    echo "${package} already installed"
  fi
done

cd ~
# link .vimrc
ln -s .vimrc ~/.vimrc || true
