#!/bin/bash

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi

# install Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle

# install plugins 
git clone https://tpope.io/vim/dispatch.git
git clone https://github.com/ntpeters/vim-better-whitespace.git
git clone https://github.com/terryma/vim-multiple-cursors.git

# fzf
git clone https://github.com/junegunn/fzf.vim.git

# Airline
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/vim-airline/vim-airline-themes

# Git
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/airblade/vim-gitgutter

# Snipmate
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git
git clone https://github.com/garbas/vim-snipmate.git
git clone https://github.com/honza/vim-snippets.git

# tagbar
git clone https://github.com/majutsushi/tagbar.git

# NERDCommenter
git clone https://github.com/scrooloose/nerdcommenter.git

cd ~
# link .vimrc
ln -s .vimrc ~/.vimrc
